import "./globals.css";
import Footer from "./footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#CACACA]  mx-auto">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
